export { VaultIndex } from "./durable/vault-index";
export { createVaultService, type VaultService, type VaultDocuments, type VaultDocumentMetadata } from "./service";
export { backlinkTargets, scanTextFiles } from "./document/r2";
export { backupTextDocument, moveDocument } from "./document/objects";
export { createMutationRecorder, type RecordMutationInput, type RecordedMutation } from "./mutation/recorder";
export { createMutationIngress, handleMutationIngressRequest, MutationIngressError, createR2MutationVerifier } from "./mutation/http";
export { isRemoteApply, normalizeEtag, parseIngressBody, recordVerifiedMutation } from "./mutation/ingress";
export { MUTATION_SOURCES, isMutationEvent, isMutationSource, type BroadcastState, type JournalEntry, type MutationEvent, type MutationRecord, type MutationSource } from "./mutation/types";
export { createMutationId, isMutationId, mutationLog, pathDigest } from "./mutation/ids";
export { INDEX_ACTIONS, OBSIDIAN_INDEX_DEBOUNCE_MS, indexIntentsFor, indexNotBefore, type IndexAction, type IndexIntent } from "./index/intents";
export { drainDueIndex, type NoteIndexer } from "./index/scheduler";
export { createGatewayPublisher } from "./sync-publisher/gateway-rpc";
export { drainSyncOutbox, publishMutation } from "./sync-publisher/publisher";
export { SqlMutationStore, type SqlDatabase } from "./index/journal-store";
export { MemoryMutationStore } from "./index/memory-store";
export { journalFromStore, type MutationJournal, type MutationStore } from "./mutation/store";
